# Generated by Django 5.0.7 on 2024-08-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile/default.jpg', upload_to='profile/'),
        ),
    ]
